### ISSUE TITLE
No indication of required fields

### ISSUE THREAD

**Issue by phoenix-23** [mohitg20/TA-Reimbursement-Project#10]
**Bug Description**
Whenever any **required** field is left empty in the application form, the user is shown the error message "_This field is required_" but there is no indication as to which fields are actually required.

**Screenshot**
Below is a screenshot depicting the error message
![image](https://user-images.githubusercontent.com/63054259/164061298-0b245783-c28a-424a-aa7a-462753f1cf6e.png)

**Desktop Specifications:**
 - OS: Windows 10 Home
 - Browser: Brave
 - Version: 1.37.116

**Comment by phoenix-23** [comment]
The same needs to be done with the 'Claim Bill' form too

**Comment by mandar7-git** [comment]
I have resolved the same thing for 'Claim Bill' before 'Application Form' (you could go through the commit history). I just didn't mention this issue in the comment. In the latest version, you can check both of them.

**Comment by phoenix-23** [comment]
Currently, there still aren't any indications like an asterisk '*' mark alongside compulsory fields.
Is there any other indication that was provided?

**Comment by mandar7-git** [comment]
After the latest Pull Request is closed, you would see asterisks beside the required fields. Also, if any of those fields are not filled, it takes the user to that particular field (and displays a message asking the user to fill it).

**Comment by phoenix-23** [comment]
Issue Resolved. Thank you!
