### ISSUE TITLE
Cannot Submit Application Form

### ISSUE THREAD

**Issue by phoenix-23** [mohitg20/TA-Reimbursement-Project#11]
**Bug Description**
Following the issue #8 and #10 , I, as a user, am unable to submit an application form because the "Roll No." field remains blank (as the profile details cannot be updated). Filling the form correctly and clicking on the "Submit" button displays the error message "This field is required". This issue needs to be resolved urgently as till this issue is not resolved, it is not possible for beta testers to proceed forward in testing subsequent features which are valid only after a form is submitted.

**Comment by nsingla20** [comment]
This issue was due to #8 as the Roll No. field was imported from the profile in the application but the user wasn't able to submit Profile
#15 has corrected redirection to Profile before filling application form
9568028bcd944ef379a34c2281e25ed2626a263f has corrected profile auto-fill issue

**Comment by phoenix-23** [comment]
The issue has been resolved.. Thank You !
