### ISSUE TITLE
Incorrect dates in the 'Date' Field

### ISSUE THREAD

**Issue by phoenix-23** [mohitg20/TA-Reimbursement-Project#25]
**Bug Description**
The 'Date' Field of the application form takes any input as correct input. Even dates like 00/00/0000 are considered as correct input.

**Screenshots**
![image](https://user-images.githubusercontent.com/63054259/164891492-ffb5afed-b751-49bb-9bc8-acc93633642b.png)

**Comment by nsingla20** [comment]
Issue corrected in f798834526cc631bd235e50fad99a3b53c45e4d2

**Comment by phoenix-23** [comment]
Issue resolved. Thank You !
