### ISSUE TITLE
Wrong Email ID on Profile Page

### ISSUE THREAD

**Issue by phoenix-23** [mohitg20/TA-Reimbursement-Project#9]
**Bug Description**
The "Email" field on the profile page displays the wrong email id. It displays the same dummy email id user@iitk.ac.in for all users. Here, the email with which I registered was harshku@iitk.ac.in but it displays user@iitk.ac.in.

**Screenshots**
Below is a screenshot depicting the bug.
![image](https://user-images.githubusercontent.com/63054259/164056499-0e92c01b-7c63-4fa7-a3ec-bcb9e1c4d684.png)

**Desktop Specifications:**
 - OS: Windows 10 Home
 - Browser: Brave
 - Version: 1.37.116

**Comment by arnav4567** [comment]
The bug has been resolved by #12 . The email field now shows the correct email id for all users.

**Comment by phoenix-23** [comment]
This issue has been resolved. Thank You !
